### ISSUE TITLE
Brandenburg: Schulname in Adresse

### ISSUE THREAD

**Issue by mojeffski** [Datenschule/jedeschule-scraper#11]
Schulname ist in der Adresszeile verpackt. Schulname teilweise mit Anführungszeichen geschrieben. 
Feld Besonderheit bei 77% ausgefüllt.

https://app.scrapinghub.com/p/126463/5/1/items

**Comment by k-nut** [comment]
@knutator2 das ist glaube ich etwas, das wir dann im Items Pipeline Prozess bearbeiten würden, oder? Denn der Scraper an sich liefer ja die richtigen Daten zurück, wir müssen sie nur anders auftrennen und abspeichern.

**Comment by knutator2** [comment]
not relevant anymore
