### ISSUE TITLE
Update Sachsen Scraper

### ISSUE THREAD

**Issue by knutator2** [Datenschule/jedeschule-scraper#114]
There is an API now under https://schuldatenbank.sachsen.de/docs/api.html to get scools from sachsen. The scraper should use the API instead of scraping the html

**Comment by cyroxx** [comment]
As a first insight, https://schuldatenbank.sachsen.de/api/v1/schools?offset=0 gives you the list of schools.
However, the API uses a lot of ids/keys, which need to be mapped using the other endpoints in order to retrieve a useful result.
