### ISSUE TITLE
Saarland: Felder "telephone" & "director" kein Inhalt

### ISSUE THREAD

**Issue by mojeffski** [Datenschule/jedeschule-scraper#15]
Inhalt der Felder:"null". Vielleicht weil Felder im Schulverzeichnis geschützte Leerzeichen enthalten? (&nbsp) Einzige Gemeinsamkeit...

Link Scrapinghub:
https://app.scrapinghub.com/p/126463/3/1/items

Link Schulverzeichnis:
http://www.saarland.de/SID-79B21F8D-2276356E/4623.htm

**Comment by k-nut** [comment]
@mojeffski ich mache den Issue noch mal auf, damit du überprüfen kannst, ob es jetzt tatsächlich behoben ist. Wenn ja, dann kannst du ihn gerne wieder schließen :)
