### ISSUE TITLE
NRW: Internet

### ISSUE THREAD

**Issue by mojeffski** [Datenschule/jedeschule-scraper#17]
Feld Internet nur bei 33 % vorhanden. Allerdings ist das Feld leer ("").
https://app.scrapinghub.com/p/126463/10/1/items?filterField=Internet&filterAction=exists&projectId=126463&spiderId=10&jobId=1

**Comment by k-nut** [comment]
Das scheint in der aktuellen Version nicht mehr der Fall zu sein: https://app.scrapinghub.com/p/126463/10/3/items?filterField=Internet&filterAction=exists
