### ISSUE TITLE
NRW: Schulform enthält Schulname

### ISSUE THREAD

**Issue by mojeffski** [Datenschule/jedeschule-scraper#18]
Im Feld Schulform ist der Name der Schule enthalten. Im Feld "Amtliche Bezeichnung" ist Schulname + Schulform. Uneinheitlich strukturiert.
https://app.scrapinghub.com/p/126463/10

**Comment by knutator2** [comment]
Bei Schulform steht jetzt wirklich die Schulform. Ich hab auch noch ne zweite Version des Schulnamens aus der initialen Schulliste. Ist aber eigentlich noch schlimmer. Ich würde sagen, wir nehmen einfach "amtliche Schulbezeichnung"

**Comment by cyroxx** [comment]
Vermutlich obsolet dank #35?

**Comment by knutator2** [comment]
jep, das ticket ist ein wenig outdated
