### ISSUE TITLE
MV: Schulname

### ISSUE THREAD

**Issue by mojeffski** [Datenschule/jedeschule-scraper#20]
Spalte Schulname nicht einheitlich strukturiert. Hier Beispiele: 
1. Gehlsdorfer Grundschule, Rostock

2. Grundschule "John Brinckman", Rostock

3. "Schule am Schäferteich" - Schule mit dem Förderschwerpunkt Lernen - Regionales Förderzentrum Toitenwinkel

4. Förderzentrum am Schwanenteich - Schule mit dem Förderschwerpunkt Lernen

**Comment by knutator2** [comment]
not relevant anymore
