### ISSUE TITLE
NRW - Verschiedene Tabellenformate scrapen: https://www.schulministerium.nrw.de/BiPo/SchuleSuchen/online?action=164.7592850805142&SNR=166832

### ISSUE THREAD

**Issue by knutator2** [Datenschule/jedeschule-scraper#22]

**Comment by knutator2** [comment]
Beispiel: https://www.schulministerium.nrw.de/BiPo/SchuleSuchen/online?action=164.7592850805142&SNR=166832

**Comment by cyroxx** [comment]
Eventuell sind die Infos mittlerweile bereits als XML und CSV verfügbar, siehe https://www.schulministerium.nrw.de/docs/bp/Ministerium/Open_MSB/Open_Data/index.html.

Zu den Quellen "Schulgrunddaten NRW" sowie den Schülerzahlen, auf denen #35 basiert, sind für die Schulebene dort noch folgende Daten verfügbar
* Bilinguale Unterrichtsangebote an den Schulen in NRW
* Genehmigte Förderschwerpunkte der Förderschulen in NRW
* Internationale Kontakte der Schulen in NRW
* Kurse in der Gymnasialen Oberstufe der Gymnasien/Gesamtschulen in NRW

Wahrscheinlich kann man damit erstmal anfangen und dann gucken, was im Gegensatz zu der Webseite ggf. noch fehlt.

**Comment by k-nut** [comment]
Können wir diesen Issue schließen und stattdessen den Code aus #77 benutzen? Langfristig würde ich auf jeden Fall lieber auf von den Ländern bereitgestelltes Open Data zurückreifen statt ihre Seiten zu scrapen.

**Comment by knutator2** [comment]
+1. scheinen ja auch alle Daten die wir erstmal brauchen da zu sein
