### ISSUE TITLE
Niedersachsen: Felder fehlen

### ISSUE THREAD

**Issue by mojeffski** [Datenschule/jedeschule-scraper#24]
Die Felder Straße und Ort solten ncoh mitgescraped werden. Und insbesondere das Feld: "Besonderheit". Hier gibt es glaub ich die spannendsten Ergebnisse für Niedersachsen...

**Comment by knutator2** [comment]
lag an der Scrapy Pipeline. Hab sie erstmal abgestellt auf scrapinghub bis sie fertig ist.
