### ISSUE TITLE
Lizenz

### ISSUE THREAD

**Issue by heyarne** [Datenschule/jedeschule-scraper#27]
Unter welcher Lizenz wird der Code gehalten? Die einzige Info, die ich dazu gefunden habe, ist [folgende](https://jedeschule.de/daten/):

> Alle Daten zum Projekt sind unter CC0 als Open Data frei zugänglich und können heruntergeladen werden.
>
> Den Quellcode der Webseite JedeSchule.de, die Dokumentation und alle Schuldaten-Scraper sind als Open Source auf www.github.com/datenschule verfügbar.

**Comment by knutator2** [comment]
Hey @heyarne ich habe mal ein LICENSE file hinzugefügt. Ist alles MIT kannst du frei benutzen.
