### ISSUE TITLE
Bremen Feld Ansprechperson

### ISSUE THREAD

**Issue by mojeffski** [Datenschule/jedeschule-scraper#3]
Ansprechperson: Schulleiter und Vertretung in einem Feld ( im json durch \n abgetrennt)
ggf. in zwei Felder aufteilen?

**Comment by knutator2** [comment]
leider etwas komplizierter. Ich glaube wir müssten im Wort vor dem Doppelpunkt in key Value Pairs auftrennen

**Comment by knutator2** [comment]
not relevant anymore
