### ISSUE TITLE
installer broken

### ISSUE THREAD

**Issue by tursics** [Datenschule/jedeschule-scraper#31]
I tried to run the install script but it seems to be broken:

`Collecting de-core-news-md==1.0.0 (from -r requirements.txt (line 24))
  Could not find a version that satisfies the requirement de-core-news-md==1.0.0 (from -r requirements.txt (line 24)) (from versions: )
No matching distribution found for de-core-news-md==1.0.0 (from -r requirements.txt (line 24))`

`Collecting en-core-web-sm==1.2.0 (from -r requirements.txt (line 28))
  Could not find a version that satisfies the requirement en-core-web-sm==1.2.0 (from -r requirements.txt (line 28)) (from versions: )
No matching distribution found for en-core-web-sm==1.2.0 (from -r requirements.txt (line 28))`

`Collecting normdatei==0.2 (from -r requirements.txt (line 68))
  Could not find a version that satisfies the requirement normdatei==0.2 (from -r requirements.txt (line 68)) (from versions: )
No matching distribution found for normdatei==0.2 (from -r requirements.txt (line 68))`

**Comment by tursics** [comment]
followed by a `error: could not create '/Library/Python/2.7/site-packages/sqlalchemy': Permission denied`

I used `sudo pip install -r requirements.txt` but get:

`wfs-downloader 1.0.0 has requirement lxml==3.7.3, but you'll have lxml 4.1.1 which is incompatible.`

I give up,
Thomas

**Comment by tursics** [comment]
This issue will be closed in #32

**Comment by k-nut** [comment]
Fixed in #32
