### ISSUE TITLE
NRW: Scraper aktualisieren

### ISSUE THREAD

**Issue by cyroxx** [Datenschule/jedeschule-scraper#34]
Der Scraper für NRW liefert aktuell nur ein leeres Ergebnis (`[]`).

Die neue Einstiegsseite sollte vermutlich diese sein: https://www.schulministerium.nrw.de/BiPo/SchuleSuchen/online?action=829.4479020997484

@lislis, da du zuletzt im April neue Daten für NRW bereitgestellt hast (Datenschule/schulscraper-data@c4f14d314799a37e022cfd8f0f62a121acac73b7): Hast du vielleicht schon eine Version des Scrapers, der mit der geänderten Website umgehen kann?

**Comment by lislis** [comment]
Hey @cyroxx, Update des Datensatzes im April war quasi nur ein neu formatiertes (gemergtes) CSV aus den schon gescrapten Rohdaten (die schul-id hatte gefehlt). Gescrapt wurden die Daten seit 2 Jahren nicht mehr.  
Ich pinge mal @knutator2 der ursprünglich den scraper geschrieben hat für eine Einschätzung der Lage.

**Comment by k-nut** [comment]
Hey, ich war damals auch an der Entwicklung beteiligt. Soweit ich das sehe, lässt sich die neue Seite leider deutlich schlechter scrapen als die alte. Man kommt immer noch an die Liste aller Schulen ran, indem man eine leere Suche ausführt, auf der Detailseite der Schulen gibt es aber keine Tabelle mehr sondern nur noch eine durch `<br />`s getrennte Liste mit den Daten über die Schule. Da müsste man wahrscheinlich mit ein bisschen Regex-Matching die Informationen extrahieren.

Der Code könnte dafür ungefähr so aussehen:

```python
class NRWSpider(scrapy.Spider):
    name = "nrw"
    base_url = "https://www.schulministerium.nrw.de"

    start_urls = ['https://www.schulministerium.nrw.de/BiPo/SchuleSuchen/online']

    def parse(self, response):
        url = response.css("[name='suche_name']::attr(action)").extract_first().strip()
        return scrapy.Request(self.base_url + url, callback=self.parse_search)

    def parse_search(self, response):
        search_button_props = {"value": "suchen"}
        return scrapy.FormRequest.from_response(response, callback=self.parse_schoollist, clickdata=search_button_props)

    def parse_schoollist(self, response):
        for tile in response.css('.kachelBodySchuleSuchen'):
            collection = {}
            collection['Schulform'] = tile.css('.kachelHeading::text').extract_first().strip()
            url = tile.css('a::attr(href)').extract_first().strip()
            request = scrapy.Request(self.base_url + '/BiPo/SchuleSuchen/' + url, callback=self.parse_overview)
            request.meta['collection'] = collection
            response.collection = collection
            yield request

    def parse_overview(self, response):
        inspect_response(response, self)
        collection = response.meta['collection']
        # Extract unformatted content from the `kachelBodySchulInfo` here
        # collection['Name'] = <finde name>
        # ...
        yield collection
```

**Comment by cyroxx** [comment]
Es gibt auch ein OpenData-Angebot: https://www.schulministerium.nrw.de/BiPo/OpenData/Schuldaten/schuldaten.xml ;-)

Das könnte man ähnlich wie für Hamburg dann z. B. so einlesen:

```python
def get_nrw():
    url = 'https://www.schulministerium.nrw.de/BiPo/OpenData/Schuldaten/schuldaten.xml'
    r = requests.get(url)
    r.encoding = 'utf-8'
    elem = etree.fromstring(r.content)
    data = []
    for member in elem:
        print(member)
        data_elem = {}
        for attr in member:
            print(attr)
            data_elem[attr.tag] = attr.text
        data.append(data_elem)
    print('Parsed ' + str(len(data)) + ' data elements')
    with open('data/nrw.json', 'w', encoding='utf-8') as json_file:
        json_file.write(json.dumps(data))
```
Zusatzinfos wie Schülerzahlen, Förderschwerpunkte und bilinguale Unterrichtsangebote müsste man sich dann aus den anderen Dateien noch dazuholen, aber das wäre ja alles machbar.
Mehr Infos zum Datenbestand:
https://www.schulministerium.nrw.de/docs/bp/Ministerium/Open_MSB/Open_Data/index.html

**Comment by k-nut** [comment]
Oh, das sieht ja richtig vielversprechend aus! Hast du Lust, da einen kleinen PR draus zu machen? Ich glaube die Zusatzinfos könnten wir erst mal weg lassen, wichtiger scheint es mir, dass die Daten aktuell sind.
