### ISSUE TITLE
update scrapers

### ISSUE THREAD

**Issue by knutator2** [Datenschule/jedeschule-scraper#39]
update the scrapers for all federal states

- [x] Nordrhein-Westfalen
- [x] Niedersachsen
- [ ] Bayern
- [ ] Rheinland-Pfalz
- [x] Hessen
- [x] Saarland
- [ ] Berlin (Pending PR: ~~#46~~ #81)
- [ ] Brandenburg (Pending PR: #45)
- [ ] Schleswig-Holstein
- [ ] Mecklenburg-Vorpommern (#58)
- [x] Thüringen
- [ ] Sachsen (#52)
- [ ] Sachsen-Anhalt (#53)
- [ ] Bremen
- [x] Baden-Württemberg
- [ ] Hamburg

**Comment by cyroxx** [comment]
@cursorius-cursor has updated and rewritten the MV scraper: https://github.com/cursorius-cursor/jedeschule-scraper/commit/9bb489bb6ed7150debae2a3f46a43303266e8987

Apart from fixing the scraper, the biggest change is that almost all keys/abbreviations are directly read from the Excel file (except for those that are missing from the legend).
