### ISSUE TITLE
Sachsen Titel

### ISSUE THREAD

**Issue by mojeffski** [Datenschule/jedeschule-scraper#4]
Titelfeld: Lediglich Schulform + Nummer wird gegeben. Frage: reicht das aus, um Schulen später mit z.B. externen Bildungsangeboten zu matchen?

**Comment by knutator2** [comment]
nope, guter punkt. Wir müssen uns einen eindeutigen identifier ausdenken. Ist etwas kompliziert, weil sich schulnummern ändern können

**Comment by k-nut** [comment]
Machen wir auch in der Item Pipeline oder so.

**Comment by knutator2** [comment]
not relevant anymore
