### ISSUE TITLE
Add Scrapy option to non-scrapy crawlers?

### ISSUE THREAD

**Issue by cyroxx** [Datenschule/jedeschule-scraper#42]
For the sake of an experiment, I converted my WIP crawler for Hessen into a Scrapy spider: cyroxx/jedeschule-scraper@0263e41711eeddc7ca57e8c460f2bb898f59f77a

Is this an approach that we should consider for those crawlers that are not yet scrapy based - at least as a second option? This would allow us to implement scrapy pipelines with them and use them on ScrapingHub.

**Comment by k-nut** [comment]
I think for the sake of having all the scrapers run through the pipelines and on scraping hub this is a really good idea!

**Comment by knutator2** [comment]
+1

**Comment by knutator2** [comment]
can we close this one? @cyroxx @k-nut

**Comment by k-nut** [comment]
Yes, I think we have an agreement that this is a good idea ;)
