### ISSUE TITLE
Sachsen: Wdh. in "Anzahl der Lehrerinnen und Lehrer" Wdh. in "Zusätzliches Personal"

### ISSUE THREAD

**Issue by mojeffski** [Datenschule/jedeschule-scraper#5]
Anzahl der Lehrerinnen und Lehrer: 
Wird für mehrere Jahre angegeben. Ältester Eintrag enthält falsche Werte. Überschriften aus 
"technisches Personal" als Eintrag.

Zusätzliches Personal:
Hier werden die Werte aus technischem Personal gelistet. Obwohl im Verzeichnis "An der Schule ist kein zusätzliches Personal tätig" eingetragen ist. Nachschauen, wie Werte strukturiert sind wenn technisches Personal vorhanden ist.

**Comment by knutator2** [comment]
not relevant anymore
