### ISSUE TITLE
Fix MV spider again (2019/2)

### ISSUE THREAD

**Issue by cyroxx** [Datenschule/jedeschule-scraper#58]
Unfortunately, the file located under http://service.mvnet.de/_php/download.php?datei_id=1614165 does not exist anymore :(

**Comment by cyroxx** [comment]
On the page https://www.regierung-mv.de/Landesregierung/bm/Ministerium/Statistik/, there is a link "[Schulverzeichnis für das Schuljahr 2019/2020](https://service.mvnet.de/_php/download.php?datei_id=1619185)":

![grafik](https://user-images.githubusercontent.com/1298447/70009028-ef17f080-1572-11ea-96e1-00693e711e83.png)

**Comment by knutator2** [comment]
yep, already started working on this. I will push it in the next couple of days

**Comment by k-nut** [comment]
@knutator2 do you still have your code for this lying around somewhere? It would also be a good time to convert  this into a proper python scraper for consistency. That combined with #77 would actually allow us to remove `run.py` entirely.

**Comment by k-nut** [comment]
This was done in #103
