### ISSUE TITLE
Sachsen Schultitel: Sehr unstrukturiert

### ISSUE THREAD

**Issue by mojeffski** [Datenschule/jedeschule-scraper#6]
bisher 3 Versionen gefunden: 
1. Schulename, Grundschule
2. Grundschule Schulname
3. Grundschule "Schulname"

Hier ggf nach Namen der Schulformen suchen? Wenn davor noch ein Komma steht nach ",Schulform" (als regex anpassen) suchen? Extrahierte Werte als extra Feld Schulform anlegen.

**Comment by knutator2** [comment]
not relevant anymore
