### ISSUE TITLE
Document need for Python 3.8

### ISSUE THREAD

**Issue by stefanw** [Datenschule/jedeschule-scraper#65]
cc10fe450bbac399631647a5e2ca3b92104784d9 introduced the need for Python 3.8. Maybe document that or put it in `setup.py`?

**Comment by k-nut** [comment]
@stefanw is it 3.8 or 3.7? We are using dataclasses and type annotation which are both 3.7 features, no?

I created a PR to document this here: https://github.com/Datenschule/jedeschule-scraper/pull/create?base=Datenschule%3Amaster&head=Datenschule%3Apython-3-7-doc
