### ISSUE TITLE
TypeError: 'SchoolPipelineItem' object is not a mapping

### ISSUE THREAD

**Issue by stefanw** [Datenschule/jedeschule-scraper#66]
The `SchoolPipelineItem` is a `dataclass` which apparently does not support being `**` into a dict:

```
session.query(School).filter_by(id=item.info['id']).update({**item, 'raw': item.item})
TypeError: 'SchoolPipelineItem' object is not a mapping
```

**Comment by stefanw** [comment]
Looking at this a bit closer [this line](https://github.com/Datenschule/jedeschule-scraper/blob/master/jedeschule/pipelines/db_pipeline.py#L41) should probably be `**item.info`, right @k-nut ?

**Comment by k-nut** [comment]
Nice catch. Adresse here: https://github.com/Datenschule/jedeschule-scraper/pull/68/files

**Comment by cyroxx** [comment]
Closing this since #68 got already merged.
