### ISSUE TITLE
 schleswig-holstein: doppelte Felder bei Email, Straße, PLZ

### ISSUE THREAD

**Issue by mojeffski** [Datenschule/jedeschule-scraper#7]
Bei 154 (19%) ist das Emailfeld doppelt angegeben. Einmal als "Email" und "EMail".
Wenn "EMail" angegeben ist, ist das richtige Email-Feld leer. Ggf löschen und umbenennen ?

Ebenfalls bei den 154 Schulen ist einmal das Feld "Straße" und das Feld "Straße und Hausnummer" zu finde. Jedoch stehen hier zwei unterschiedliche Straßen. Handelt es sich hier um Fusionsschulen? 

Hier ebenfalls doppelt die Felder PLZ und Postleitzahl.

**Comment by knutator2** [comment]
Hey Moritz,
kannst du am besten immer noch nen Link aus dem scrapinghub posten? Dann finden wir das schneller

**Comment by knutator2** [comment]
not relevant anymore
