### ISSUE TITLE
SN: Investigate API

### ISSUE THREAD

**Issue by cyroxx** [Datenschule/jedeschule-scraper#70]
Using our current crawler for Sachsen, I found an API:
https://schuldatenbank.sachsen.de/api/v1/schools

There is a lot of nice data (for example, schools and their different buildings are distinguishable), but I cannot see where the keys like `school_category_key`, `company_number` and the like) are described.

**Comment by k-nut** [comment]
Maybe we can simply ask them kindly for some kind of API documentation? And if they don't reply, we could actually send a Freedom of Information request?

**Comment by knutator2** [comment]
has someone already asked about the api? otherwise i will do it

**Comment by cyroxx** [comment]
no, i haven't asked for the documentation yet.

**Comment by k-nut** [comment]
@knutator2 is awaiting an official reply

**Comment by knutator2** [comment]
turns out there is even a very nice Fast API Documentation 🥳 

https://schuldatenbank.sachsen.de/docs/api.html

I was told, that the documention will also be available on their website in a couple of Days. I think we should use this in our scrapers

**Comment by knutator2** [comment]
closing this issue, because its clear there is an API Documentation and opened a new ticket #114 to update the scraper
