### ISSUE TITLE
[SL] Update start URL for Saarland Scraper

### ISSUE THREAD

**Issue by k-nut** [Datenschule/jedeschule-scraper#74]
The current Saarland Scraper fails with a 404. 
I did some research and found that the data is now published here: https://www.saarland.de/mbk/DE/portale/bildungsserver/themen/schulen-und-bildungswege/schuldatenbank/_functions/Schulsuche_Formular.html?input_=4f580d64-ee10-4fe2-9536-a2179ebd8050&submit=Suchen&resourceId=f39c05c4-c261-4040-975e-081ccd54c9a0&pageLocale=de

And empty search is still possible luckily for us and this seems like a very straightforward thing to scrape, it does not even have detail pages.

**Comment by k-nut** [comment]
@cyroxx do you know if anyone is already working on this?

**Comment by cyroxx** [comment]
Closing this as the Saarland scraper was re-written in #87 in order to deal with the changes.
